-- ============================================
-- UNCANNY MVP — Content Seed
-- Run AFTER supabase-schema.sql
-- ============================================
-- 
-- HOW TO USE:
-- 1. Go to Supabase Dashboard → SQL Editor
-- 2. First run supabase-schema.sql (if you haven't)
-- 3. Then run this file
-- 4. Replace AI image URLs with your actual generated images
--
-- TIPS:
-- • Real images: Use Unsplash URLs (free, no signup)
-- • AI images: Generate with Midjourney/Leonardo/DALL-E
--   then upload to Imgur and use the direct link
-- • Each day needs exactly 5 challenges (set_order 1-5)
-- • Mix of 'ai' and 'real' answers per day
-- • difficulty: 1=easy to spot, 5=nearly impossible
-- ============================================

-- Clear existing sample data (safe for fresh installs)
DELETE FROM challenges;

-- ============================================
-- DAY 1 — Today (3 real, 2 AI)
-- ============================================
INSERT INTO challenges (set_date, set_order, image_url, answer, difficulty, context_short, ai_prompt, source_credit) VALUES

-- 1. REAL — Dramatic landscape
(CURRENT_DATE, 1,
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 'real', 2,
 'A real sunset over the Swiss Alps. Nature doesn''t need a GPU.',
 NULL,
 'Unsplash / Samuel Ferrara'),

-- 2. AI — Replace this URL with your AI-generated image
(CURRENT_DATE, 2,
 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=800',
 'ai', 3,
 'This stunning portrait was entirely generated by AI. Every pore, every strand of hair — artificial.',
 'hyperrealistic portrait, studio lighting, 8k, photorealistic --v 6',
 'Midjourney v6'),

-- 3. REAL — Nature macro
(CURRENT_DATE, 3,
 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800',
 'real', 3,
 'A real nebula captured by the Hubble telescope. Space is stranger than AI.',
 NULL,
 'NASA/ESA Hubble Heritage'),

-- 4. AI — Replace this URL with your AI-generated image
(CURRENT_DATE, 4,
 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
 'ai', 4,
 'AI-generated landscape that fooled 73% of viewers. The reflections gave it away.',
 'misty mountain lake, golden hour, photorealistic landscape photography --v 6',
 'Midjourney v6'),

-- 5. REAL — Urban/architecture
(CURRENT_DATE, 5,
 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800',
 'real', 2,
 'Real Tokyo street at night. Blade Runner wishes it looked this good.',
 NULL,
 'Unsplash / Jezael Melgoza');


-- ============================================
-- DAY 2 — Tomorrow (2 real, 3 AI)
-- ============================================
INSERT INTO challenges (set_date, set_order, image_url, answer, difficulty, context_short, ai_prompt, source_credit) VALUES

-- 1. AI
(CURRENT_DATE + 1, 1,
 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
 'ai', 3,
 'This plate of food never existed. Every grain of rice was computed.',
 'overhead food photography, michelin star dish, natural lighting --v 6',
 'DALL-E 3'),

-- 2. REAL
(CURRENT_DATE + 1, 2,
 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
 'real', 2,
 'A real portrait with perfect natural lighting. No prompt needed.',
 NULL,
 'Unsplash / Joseph Gonzalez'),

-- 3. AI
(CURRENT_DATE + 1, 3,
 'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=800',
 'ai', 4,
 'AI aurora borealis. The colors are too perfect — that''s the tell.',
 'northern lights over snowy mountains, 8k photography, realistic --v 6',
 'Midjourney v6'),

-- 4. REAL
(CURRENT_DATE + 1, 4,
 'https://images.unsplash.com/photo-1494587416117-f102a2ac0a8d?w=800',
 'real', 4,
 'A perfectly symmetrical flower. Evolution is the original designer.',
 NULL,
 'Unsplash / Annie Spratt'),

-- 5. AI
(CURRENT_DATE + 1, 5,
 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
 'ai', 5,
 'Indistinguishable from real. This starry sky was generated in 30 seconds.',
 'astrophotography, milky way over mountains, long exposure style --v 6',
 'Midjourney v6');


-- ============================================
-- DAY 3 — Day after tomorrow (3 real, 2 AI)
-- ============================================
INSERT INTO challenges (set_date, set_order, image_url, answer, difficulty, context_short, ai_prompt, source_credit) VALUES

-- 1. REAL
(CURRENT_DATE + 2, 1,
 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
 'real', 1,
 'Mountain peaks at golden hour. Raw, untouched landscape.',
 NULL,
 'Unsplash / Kalen Emsley'),

-- 2. AI
(CURRENT_DATE + 2, 2,
 'https://images.unsplash.com/photo-1485550409059-9afb054cada4?w=800',
 'ai', 3,
 'AI-generated macro insect photography. The wings are mathematically perfect — too perfect.',
 'macro butterfly wing, extreme detail, studio lighting --v 6',
 'Leonardo AI'),

-- 3. REAL
(CURRENT_DATE + 2, 3,
 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=800',
 'real', 4,
 'Real bioluminescent plankton lighting up the shore. Nature''s own LED display.',
 NULL,
 'Unsplash / Ishan @seefromthesky'),

-- 4. REAL
(CURRENT_DATE + 2, 4,
 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800',
 'real', 2,
 'Close-up of ice crystals on a window. Nature''s fractals.',
 NULL,
 'Unsplash / Aaron Burden'),

-- 5. AI
(CURRENT_DATE + 2, 5,
 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
 'ai', 5,
 'This Patagonia-style landscape was generated in under a minute. Zero cameras were used.',
 'dramatic patagonia landscape, photorealistic, award winning photography --v 6',
 'Midjourney v6');


-- ============================================
-- VERIFY: Check your data
-- ============================================
-- SELECT set_date, set_order, answer, difficulty, 
--        LEFT(context_short, 40) as preview
-- FROM challenges 
-- ORDER BY set_date, set_order;
