// ── Uncanny Shared Fallback Challenges ──

export interface FallbackChallenge {
  id: string;
  image_url: string;
  answer: 'ai' | 'real';
  difficulty: number;
  set_order: number;
  context_short: string;
  ai_prompt: string | null;
  source_credit: string;
  photographer_name?: string | null;
  photographer_url?: string | null;
  unsplash_url?: string | null;
}

export const FALLBACK_CHALLENGES: Record<number, FallbackChallenge[]> = {
  1: [ // reflection-1, set_order 6-8
    {
      id: 'bceed60c-65ff-4b89-b55b-6a539da92797',
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/50fce744-231e-472d-8e03-b4f4f9b2c1cb.jpg',
      answer: 'ai',
      difficulty: 3,
      set_order: 6,
      context_short: 'A modern chair sitting on a concrete patio in soft fog. Rendered synthetically.',
      ai_prompt: 'A modern designer chair sitting on a concrete patio, light fog, shot on 35mm film.',
      source_credit: 'AI Generated'
    },
    {
      id: '168cc9c0-96e2-4525-acfa-b0f165e0ff17',
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/061fad5f-4fea-4d13-8f88-765346af9b91.jpg',
      answer: 'ai',
      difficulty: 4,
      set_order: 7,
      context_short: 'A close up of mossy stones near a forest stream, damp and cold. Completely computer generated.',
      ai_prompt: 'A close-up photograph of mossy stones by a small forest stream, damp conditions, shot on digital macro lens.',
      source_credit: 'AI Generated'
    },
    {
      id: 'ddd28f19-479b-48d7-aa4c-c3d329203a6f',
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/d4ac9c9b-91d0-4158-a4ee-cb739050c4c0.jpg',
      answer: 'ai',
      difficulty: 4,
      set_order: 8,
      context_short: 'A rustic key hanging from a rusty nail against weathered green wood. Entirely artificial.',
      ai_prompt: 'A rustic key hanging on a nail in a weathered green wooden door, soft overcast light.',
      source_credit: 'AI Generated'
    }
  ],
  2: [ // reflection-2, set_order 9-10
    {
      id: '40e1b6ed-e90b-44a9-9cc4-50c8891980c2',
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/6714bc00-680a-4292-b717-817960b05fa6.jpg',
      answer: 'ai',
      difficulty: 5,
      set_order: 9,
      context_short: 'A worn-out wooden spoon resting on a speckled kitchen counter, morning light filtering in from a window. Entirely generated by AI.',
      ai_prompt: 'A worn-out wooden spoon resting on a speckled kitchen counter, morning light filtering in from a window, captured with a simple digital camera.',
      source_credit: 'AI Generated'
    },
    {
      id: 'fef7a7d5-084d-4391-b07b-68080c4cb95e',
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/21fdbfb1-9953-40a8-b6aa-e36e90df0131.jpg',
      answer: 'ai',
      difficulty: 5,
      set_order: 10,
      context_short: 'A quiet suburban street after rain, puddles reflecting the grey sky. Completely computed, every pixel artificial.',
      ai_prompt: 'A slightly blurry photo of a quiet suburban street after a light rain, puddles reflecting the grey sky, taken with a phone.',
      source_credit: 'AI Generated'
    }
  ],
  3: [ // reflection-3, set_order 11
    {
      id: '750820b0-b5cf-4352-b735-bbfc1bd740c5',
      image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800',
      answer: 'real',
      difficulty: 5,
      set_order: 11,
      context_short: 'A real deep space nebula captured by high-powered optical telescope. Perfectly organic chaos.',
      ai_prompt: null,
      source_credit: 'NASA / Unsplash',
      photographer_name: 'NASA',
      photographer_url: 'https://unsplash.com/@nasa',
      unsplash_url: 'https://unsplash.com/photos/starry-sky-photo'
    }
  ]
};
