import { GoogleGenAI } from '@google/genai';
import { getSupabaseAdmin } from '@/lib/supabase-server';

let ai: GoogleGenAI | null = null;

function getGeminiClient() {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  ai ??= new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
  return ai;
}

/**
 * Uploads a base64 encoded image to the Supabase storage bucket.
 * 
 * @param base64Data The base64 string of the image.
 * @param filename The destination filename in the bucket.
 * @returns The public URL of the uploaded image.
 */
export async function uploadGeneratedImageToStorage(base64Data: string, filename: string): Promise<string> {
  const buffer = Buffer.from(base64Data, 'base64');
  
  const supabaseAdmin = getSupabaseAdmin();
  const { data, error } = await supabaseAdmin
    .storage
    .from('challenge-images')
    .upload(`ai-generated/${filename}`, buffer, {
      contentType: 'image/jpeg',
      upsert: true
    });

  if (error) {
    throw new Error(`Failed to upload image: ${error.message}`);
  }

  const { data: { publicUrl } } = supabaseAdmin
    .storage
    .from('challenge-images')
    .getPublicUrl(data.path);

  return publicUrl;
}

/**
 * Generates an image using a free-tier generator or Gemini.
 * 
 * @param prompt The prompt for the image.
 * @returns The base64 string of the generated image.
 */
export async function generateImage(prompt: string): Promise<string> {
  const model = process.env.NANO_BANANA_MODEL || 'free-tier';

  if (model === 'free-tier' || model === 'pollinations') {
    console.log('Using Pollinations AI free-tier image generation...');
    return await generateFreeImage(prompt);
  }

  try {
    const response = await getGeminiClient().models.generateImages({
      model,
      prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
      }
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No images generated by Gemini');
    }

    const image = response.generatedImages[0];
    if (!image.image?.imageBytes) {
      throw new Error('Image bytes are missing in the response');
    }

    return image.image.imageBytes;
  } catch (err: unknown) {
    const errMsg = err instanceof Error ? err.message : String(err);
    if (errMsg.includes('paid plans') || errMsg.includes('billing') || errMsg.includes('400')) {
      console.warn('Gemini image generation requires a paid plan. Falling back to Pollinations AI (free tier)...');
      return await generateFreeImage(prompt);
    }
    throw err;
  }
}

/**
 * Generates an image using Pollinations AI (free, no API key required).
 */
async function generateFreeImage(prompt: string): Promise<string> {
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&nologo=true&private=true`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Free image generation API error: ${res.status} - ${res.statusText}`);
  }
  const arrayBuffer = await res.arrayBuffer();
  return Buffer.from(arrayBuffer).toString('base64');
}

export interface GeneratedPromptFingerprint {
  prompt: string;
  composition: 'centered' | 'wide-angle' | 'close-up' | 'macro' | 'asymmetric' | 'flat-lay';
  emotion: 'calm' | 'lonely' | 'tense' | 'cold' | 'ordinary' | 'mysterious';
  lighting: 'overcast' | 'fluorescent' | 'ambient' | 'morning-sun' | 'flash' | 'harsh-shadows';
  perspective: 'eye-level' | 'high-angle' | 'low-angle' | 'dutch-angle' | 'first-person';
  scene: 'interior' | 'street' | 'nature' | 'domestic' | 'suburban' | 'urban';
  object: string;
  texture: 'grainy' | 'smooth' | 'dusty' | 'flat' | 'glossy';
}

/**
 * Generates image prompts using Gemini text models based on real image metadata.
 * Safety and composition rules are strictly enforced.
 */
export async function generatePromptsForImages(count: number, recentMetadata: Record<string, unknown>[]): Promise<GeneratedPromptFingerprint[]> {
  const textPrompt = `
    You are an AI prompt engineer generating prompts for an image generation model.
    Generate ${count} distinct prompt objects to create AI images.
    
    Here is some metadata from recent real images we have in our database. Use these to get inspiration for topics and categories:
    ${JSON.stringify(recentMetadata, null, 2)}
    
    SAFETY RULES (MANDATORY):
    Do NOT include or imply any of the following:
    - Minors (children, kids, babies, etc.)
    - NSFW (nudity, sexual content, excessive skin, provocative poses)
    - Political figures, political symbols, or political events
    - Celebrities or known public figures
    - Violence, gore, or weapons
    - Natural or man-made disasters
    - Medical emergencies or hospitals
    - Hate symbols or discriminatory content
    - Identifiable real-person imitation
    
    AESTHETIC RULES (MANDATORY):
    - Do NOT use terms like: futuristic, neon, cyberpunk, cinematic, masterpiece, highly detailed, 8k, ultra detailed, sci-fi, glowing, dramatic lighting, photorealistic art, studio lighting, bokeh, professional.
    - Instead, aim for mundane, amateur smartphone-photo aesthetics. Lighting should be natural or ambient indoor, slightly imperfect. Focus on everyday objects, mundane scenes, simple landscapes, or ordinary situations.
    
    Make the prompts highly descriptive and focus on everyday objects, animals, landscapes, or safe abstract concepts.
    
    Output EXACTLY ${count} prompt objects as a JSON array. Each object MUST have these properties:
    - prompt: The descriptive prompt string (mundane, amateur phone style)
    - composition: "centered" | "wide-angle" | "close-up" | "macro" | "asymmetric" | "flat-lay"
    - emotion: "calm" | "lonely" | "tense" | "cold" | "ordinary" | "mysterious"
    - lighting: "overcast" | "fluorescent" | "ambient" | "morning-sun" | "flash" | "harsh-shadows"
    - perspective: "eye-level" | "high-angle" | "low-angle" | "dutch-angle" | "first-person"
    - scene: "interior" | "street" | "nature" | "domestic" | "suburban" | "urban"
    - object: The main subject category (e.g. "chair", "wire", "kitchen", "landscape", "dog")
    - texture: "grainy" | "smooth" | "dusty" | "flat" | "glossy"
    
    Do not include any markdown formatting or extra text outside of the JSON block.
  `;

  // We use gemini-2.5-flash for text/prompt generation as it's fast and reliable
  const response = await getGeminiClient().models.generateContent({
    model: 'gemini-2.5-flash',
    contents: textPrompt,
    config: {
      responseMimeType: "application/json",
    }
  });

  if (!response.text) {
    throw new Error('No text returned from Gemini prompt generation');
  }

  try {
    const prompts = JSON.parse(response.text);
    if (!Array.isArray(prompts)) {
        throw new Error('Returned prompts are not an array');
    }
    return prompts;
  } catch (err: unknown) {
    throw new Error(`Failed to parse prompt JSON from Gemini: ${(err as Error).message}`);
  }
}

