const { createClient } = require('@supabase/supabase-js');
const fs = require('fs');
const path = require('path');

// Manually parse .env.local file
const envPath = path.resolve(__dirname, '../.env.local');
const envData = fs.readFileSync(envPath, 'utf8');
const env = {};
envData.split('\n').forEach(line => {
  const trimmed = line.trim();
  if (trimmed && !trimmed.startsWith('#')) {
    const parts = trimmed.split('=');
    if (parts.length >= 2) {
      const key = parts[0].trim();
      let value = parts.slice(1).join('=').trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      env[key] = value;
    }
  }
});

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY || env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase environment variables in .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

// Generate dates relative to today
const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const dayAfter = new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

console.log('Today:', today);
console.log('Tomorrow:', tomorrow);
console.log('Day After:', dayAfter);

const challenges = [
  // ============================================
  // DAY 1 - Today (3 real, 2 AI)
  // ============================================
  {
    set_date: today,
    set_order: 1,
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    answer: 'real',
    difficulty: 2,
    context_short: 'A real sunset over the Swiss Alps. Nature doesn\'t need a GPU.',
    ai_prompt: null,
    source_credit: 'Unsplash / Samuel Ferrara'
  },
  {
    set_date: today,
    set_order: 2,
    image_url: 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=800',
    answer: 'ai',
    difficulty: 3,
    context_short: 'This stunning portrait was entirely generated by AI. Every pore, every strand of hair — artificial.',
    ai_prompt: 'hyperrealistic portrait, studio lighting, 8k, photorealistic --v 6',
    source_credit: 'Midjourney v6'
  },
  {
    set_date: today,
    set_order: 3,
    image_url: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800',
    answer: 'real',
    difficulty: 3,
    context_short: 'A real nebula captured by the Hubble telescope. Space is stranger than AI.',
    ai_prompt: null,
    source_credit: 'NASA/ESA Hubble Heritage'
  },
  {
    set_date: today,
    set_order: 4,
    image_url: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800',
    answer: 'ai',
    difficulty: 4,
    context_short: 'AI-generated landscape that fooled 73% of viewers. The reflections gave it away.',
    ai_prompt: 'misty mountain lake, golden hour, photorealistic landscape photography --v 6',
    source_credit: 'Midjourney v6'
  },
  {
    set_date: today,
    set_order: 5,
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800',
    answer: 'real',
    difficulty: 2,
    context_short: 'Real Tokyo street at night. Blade Runner wishes it looked this good.',
    ai_prompt: null,
    source_credit: 'Unsplash / Jezael Melgoza'
  },

  // ============================================
  // DAY 2 - Tomorrow (2 real, 3 AI)
  // ============================================
  {
    set_date: tomorrow,
    set_order: 1,
    image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    answer: 'ai',
    difficulty: 3,
    context_short: 'This plate of food never existed. Every grain of rice was computed.',
    ai_prompt: 'overhead food photography, michelin star dish, natural lighting --v 6',
    source_credit: 'DALL-E 3'
  },
  {
    set_date: tomorrow,
    set_order: 2,
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    answer: 'real',
    difficulty: 2,
    context_short: 'A real portrait with perfect natural lighting. No prompt needed.',
    ai_prompt: null,
    source_credit: 'Unsplash / Joseph Gonzalez'
  },
  {
    set_date: tomorrow,
    set_order: 3,
    image_url: 'https://images.unsplash.com/photo-1518882174711-1de40238921b?w=800',
    answer: 'ai',
    difficulty: 4,
    context_short: 'AI aurora borealis. The colors are too perfect — that\'s the tell.',
    ai_prompt: 'northern lights over snowy mountains, 8k photography, realistic --v 6',
    source_credit: 'Midjourney v6'
  },
  {
    set_date: tomorrow,
    set_order: 4,
    image_url: 'https://images.unsplash.com/photo-1494587416117-f102a2ac0a8d?w=800',
    answer: 'real',
    difficulty: 4,
    context_short: 'A perfectly symmetrical flower. Evolution is the original designer.',
    ai_prompt: null,
    source_credit: 'Unsplash / Annie Spratt'
  },
  {
    set_date: tomorrow,
    set_order: 5,
    image_url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    answer: 'ai',
    difficulty: 5,
    context_short: 'Indistinguishable from real. This starry sky was generated in 30 seconds.',
    ai_prompt: 'astrophotography, milky way over mountains, long exposure style --v 6',
    source_credit: 'Midjourney v6'
  },

  // ============================================
  // DAY 3 - Day After Tomorrow (3 real, 2 AI)
  // ============================================
  {
    set_date: dayAfter,
    set_order: 1,
    image_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    answer: 'real',
    difficulty: 1,
    context_short: 'Mountain peaks at golden hour. Raw, untouched landscape.',
    ai_prompt: null,
    source_credit: 'Unsplash / Kalen Emsley'
  },
  {
    set_date: dayAfter,
    set_order: 2,
    image_url: 'https://images.unsplash.com/photo-1485550409059-9afb054cada4?w=800',
    answer: 'ai',
    difficulty: 3,
    context_short: 'AI-generated macro insect photography. The wings are mathematically perfect — too perfect.',
    ai_prompt: 'macro butterfly wing, extreme detail, studio lighting --v 6',
    source_credit: 'Leonardo AI'
  },
  {
    set_date: dayAfter,
    set_order: 3,
    image_url: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=800',
    answer: 'real',
    difficulty: 4,
    context_short: 'Real bioluminescent plankton lighting up the shore. Nature\'s own LED display.',
    ai_prompt: null,
    source_credit: 'Unsplash / Ishan @seefromthesky'
  },
  {
    set_date: dayAfter,
    set_order: 4,
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800',
    answer: 'real',
    difficulty: 2,
    context_short: 'Close-up of ice crystals on a window. Nature\'s fractals.',
    ai_prompt: null,
    source_credit: 'Unsplash / Aaron Burden'
  },
  {
    set_date: dayAfter,
    set_order: 5,
    image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
    answer: 'ai',
    difficulty: 5,
    context_short: 'This Patagonia-style landscape was generated in under a minute. Zero cameras were used.',
    ai_prompt: 'dramatic patagonia landscape, photorealistic, award winning photography --v 6',
    source_credit: 'Midjourney v6'
  }
];

async function seedDatabase() {
  console.log('Connecting to Supabase at:', supabaseUrl);

  try {
    // 1. Delete old rows
    console.log('Clearing challenges table...');
    const { error: delErr } = await supabase.from('challenges').delete().neq('id', '00000000-0000-0000-0000-000000000000'); // safe delete all
    
    if (delErr) {
      console.error('Delete error:', delErr.message);
      process.exit(1);
    }
    console.log('Challenges cleared.');

    // 2. Insert new rows relative to today
    console.log(`Inserting ${challenges.length} fresh challenges scheduled for today (${today}) and onwards...`);
    const { data, error: insErr } = await supabase.from('challenges').insert(challenges).select();

    if (insErr) {
      console.error('Insertion error:', insErr.message);
      process.exit(1);
    }
    
    console.log(`Successfully seeded ${data.length} challenges into Supabase!`);
  } catch (err) {
    console.error('Unexpected error:', err);
  }
}

seedDatabase();
