import { createClient } from '@supabase/supabase-js';

const url = 'https://rahzhfgbmromdhfhunff.supabase.co';
const key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhaHpoZmdibXJvbWRoZmh1bmZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzgwMDEzOSwiZXhwIjoyMDkzMzc2MTM5fQ.2DZf6WuQ1fWpiGwp3k0tl0YCpXhLi64ji4Eqm9yjWhk';
const supabase = createClient(url, key);

async function seed() {
  const today = new Date().toISOString().split('T')[0];
  console.log("Seeding reflections for date on PRODUCTION:", today);

  // 1. Delete existing for today and set_orders 6-11
  const { error: delError } = await supabase
    .from('challenges')
    .delete()
    .eq('set_date', today)
    .in('set_order', [6, 7, 8, 9, 10, 11]);

  if (delError) {
    console.error("Delete error:", delError);
    return;
  }

  const rows = [
    {
      set_date: today,
      set_order: 6,
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/50fce744-231e-472d-8e03-b4f4f9b2c1cb.jpg',
      answer: 'ai',
      difficulty: 3,
      context_short: 'A modern chair sitting on a concrete patio in soft fog. Rendered synthetically.',
      ai_prompt: 'A modern designer chair sitting on a concrete patio, light fog, shot on 35mm film.',
      source_credit: 'AI Generated'
    },
    {
      set_date: today,
      set_order: 7,
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/061fad5f-4fea-4d13-8f88-765346af9b91.jpg',
      answer: 'ai',
      difficulty: 4,
      context_short: 'A close up of mossy stones near a forest stream, damp and cold. Completely computer generated.',
      ai_prompt: 'A close-up photograph of mossy stones by a small forest stream, damp conditions, shot on digital macro lens.',
      source_credit: 'AI Generated'
    },
    {
      set_date: today,
      set_order: 8,
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/d4ac9c9b-91d0-4158-a4ee-cb739050c4c0.jpg',
      answer: 'ai',
      difficulty: 4,
      context_short: 'A rustic key hanging from a rusty nail against weathered green wood. Entirely artificial.',
      ai_prompt: 'A rustic key hanging on a nail in a weathered green wooden door, soft overcast light.',
      source_credit: 'AI Generated'
    },
    {
      set_date: today,
      set_order: 9,
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/6714bc00-680a-4292-b717-817960b05fa6.jpg',
      answer: 'ai',
      difficulty: 5,
      context_short: 'A worn-out wooden spoon resting on a speckled kitchen counter, morning light filtering in from a window. Entirely generated by AI.',
      ai_prompt: 'A worn-out wooden spoon resting on a speckled kitchen counter, morning light filtering in from a window, captured with a simple digital camera.',
      source_credit: 'AI Generated'
    },
    {
      set_date: today,
      set_order: 10,
      image_url: 'https://rahzhfgbmromdhfhunff.supabase.co/storage/v1/object/public/challenge-images/ai-generated/2026-05-19/21fdbfb1-9953-40a8-b6aa-e36e90df0131.jpg',
      answer: 'ai',
      difficulty: 5,
      context_short: 'A quiet suburban street after rain, puddles reflecting the grey sky. Completely computed, every pixel artificial.',
      ai_prompt: 'A slightly blurry photo of a quiet suburban street after a light rain, puddles reflecting the grey sky, taken with a phone.',
      source_credit: 'AI Generated'
    },
    {
      set_date: today,
      set_order: 11,
      image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800',
      answer: 'real',
      difficulty: 5,
      context_short: 'A real deep space nebula captured by high-powered optical telescope. Perfectly organic chaos.',
      ai_prompt: null,
      source_credit: 'NASA / Unsplash',
      photographer_name: 'NASA',
      photographer_url: 'https://unsplash.com/@nasa',
      unsplash_url: 'https://unsplash.com/photos/starry-sky-photo'
    }
  ];

  const { data, error } = await supabase
    .from('challenges')
    .insert(rows);

  if (error) {
    console.error("Insert error:", error);
  } else {
    console.log("Successfully inserted production reflection challenges!");
  }
}

seed().catch(console.error);
